 
# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

updateBranch: true
#deleteBranchAfterMerge: true
reportStatus: true
mergemethod: merge

minApprovals:
  COLLABORATOR: 1
maxRequestedChanges:
  NONE: 0
blockingLabels:
- blocked
#mergeCommitMessage: |
#        {title} (#{number})
#        {body}

# Will merge whenever the above conditions are met, but also
# the owner has approved or merge label was added.
