# Add 'repo' label to any root file changes
feature:
  - api.py
  - helper.py
  - logger.py
  - api_schemas/*
  - api_schemas/**/*
  - common/*
  - common/**/*
  - config/*
  - config/**/*
  - jobs/*
  - jobs/**/*
  - reminders/*
  - reminders/**/*
  - tasks/*
  - tasks/**/*

dependencies:
  - requirements.txt

ci:
  - Makefile
  - JenkinsFile
  - Dockerfile
  - Dockerfile.base
  - .github/*
  - .github/**/*

docs:
  - README.md
  - schema/*
  - schema/**/*

chore:
  - .gitignore
