builders:
  noopBuilder:
    builder_factories:
      - noopBuilder
    import: 'package:mrigesh.dev/web_builder.dart'
    auto_apply: all_packages
    applies_builders:
      - :deploy_cleanup
    build_extensions: {}

post_process_builders:
  deploy_cleanup:
    import: 'package:mrigesh.dev/web_builder.dart'
    builder_factory: cleanupUnneededFiles
    input_extensions:
      # All files are potential inputs to delete
      - ''
    defaults:
      generate_for:
        # Globs of files to delete
        - lib/**
      # Disable in dev mode
      dev_options:
        enabled: false