targets:
  $default:
    builders:
      mrigesh.dev|copyBuilder:
        generate_for:
          - lib/*
        enabled: True

builders:
  copyBuilder:
    import: 'package:mrigesh.dev/web_builder.dart'
    builder_factories: ['copyBuilder']
    build_extensions:
      .txt:
        - .copy.txt
    build_to: source
    auto_apply: dependents