name: mrigesh.dev
description: An absolute bare-bones web app.
version: 0.0.1
homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  build: ^1.2.2
  test: ^1.9.4
  path: ^1.6.4


dev_dependencies:
  build_runner: ^1.7.2
  build_web_compilers:
  pedantic: ^1.9.0
