name: mrigesh.dev
description: An absolute bare-bones web app.
version: v0.0.1
homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  test: ^1.9.4

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
