name: Deploy Dart Web App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Cache dart dependencies
        uses: actions/cache@v1
        run: ls -l
        with:
          path: ~/.pub-cache # pub cache files are stored in `~/.pub-cache` on Linux/macOS
          key: ${{ runner.os }}-node-${{ hashFiles('**/pubspec.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: pub get &&  pub global activate webdev
      - name: Run Tests
        run: pub run test
      - name: Build Code
        run: webdev build
        env:
          PATH: $PATH:"$HOME/.pub-cache/bin"
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.5.0
        with:
          # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
          github_token:
          # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
          repository: # optional, default is
          # Destination branch to push changes
          branch: # optional, default is master
          # Determines if force push is used
          force: # optional
          # Directory to change to before pushing.
          directory: # optional, default is .
