name: Dart Development PR

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: echo $GITHUB_BASE_REF
